### ISSUE TITLE
Git.io deprecation

### ISSUE THREAD

**Issue by joshuafuller** [lennisthemenace/FreeTAKServer-Installer#6]
Just a quick heads up. 

The URL shortener in your project might stop working soon.

Link: https://github.blog/changelog/2022-04-25-git-io-deprecation/

**Comment by lennisthemenace** [comment]
"While the git.io url redirection service is [read-only](https://github.blog/2011-11-10-git-io-github-url-shortener/) and use of the service is limited, we have received feedback from developers and academic researchers who have published git.io links in print documentation and research papers. In order to preserve the integrity of these historical documents, we have decided to archive the current git.io links in a new read-only service that will allow us to serve redirects for those links longer term.

As we continue our analysis, we may remove individual links that point to spammy, malicious or 404 links. Our goal is to not break links relied on for legitimate use, especially by the academic community, while preserving the security of developers on GitHub.

That said, we still encourage users to make use of one of the many URL shortening services available with greater functionality than the git.io service provided. GitHub support will not be able to update or edit redirection records served by the git.io archive service."

Should keep working basically
